using System.CodeDom.Compiler;
using System.Reflection;
using System.Windows.Forms;
using WikiFunctions;
using WikiFunctions.CustomModules;

namespace AutoWikiBrowser;

/// <summary>
/// Provides a form for compiling and executing C# evaluator code.
/// </summary>
public partial class CSharpEval : Form
{
    /// <summary>
    /// Fully qualified name of the evaluator type generated by
    /// <see cref="BuildEvaluatorSource"/>.
    /// </summary>
    private const string EvaluatorTypeName =
        "CSharpEvaluator.CSharpEval";

    /// <summary>
    /// Initializes a new instance of the <see cref="CSharpEval"/> class.
    /// </summary>
    public CSharpEval()
    {
        InitializeComponent();
    }

    /// <summary>
    /// Compiles and executes the C# code entered in the evaluator.
    /// </summary>
    /// <param name="sender">The control that raised the event.</param>
    /// <param name="e">The event data.</param>
    private void button1_Click(
        object sender,
        EventArgs e)
    {
        textBox2.Clear();

        try
        {
            string code = BuildEvaluatorSource();

            CompilerParameters parameters = CreateCompilerParameters();

            AddLoadedAssemblyReferences(parameters);

            CompilerResults results =
                RoslynCompiler.Compile(
                    code,
                    parameters);

            if (!DisplayCompilerDiagnostics(results))
            {
                return;
            }

            InvokeEvaluator(
                results.CompiledAssembly);
        }
        catch (Exception ex)
        {
            ShowEvaluationError(ex);
        }
    }

    /// <summary>
    /// Creates the compiler configuration used when compiling evaluator code.
    /// </summary>
    /// <returns>
    /// A <see cref="CompilerParameters"/> instance configured for in-memory
    /// compilation.
    /// </returns>
    private static CompilerParameters CreateCompilerParameters()
    {
        return new CompilerParameters
        {
            GenerateExecutable = false,
            GenerateInMemory = true,
            IncludeDebugInformation = false,
            TreatWarningsAsErrors = false,
            WarningLevel = 4
        };
    }

    private string BuildEvaluatorSource()
    {
        return @"using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using WikiFunctions;

namespace CSharpEvaluator
{
    internal sealed class CSharpEval
    {
        public object EvalCode()
        {
            return " + textBox1.Text + @";
        }
    }
}
";
    }

    private static void AddLoadedAssemblyReferences(
        CompilerParameters parameters)
    {
        HashSet<string> referencePaths =
            new(StringComparer.OrdinalIgnoreCase);

        AddAssemblyReference(
            referencePaths,
            typeof(CSharpEval).Assembly);

        AddAssemblyReference(
            referencePaths,
            typeof(Tools).Assembly);

        foreach (Assembly assembly in
                 AppDomain.CurrentDomain.GetAssemblies())
        {
            if (assembly.IsDynamic)
            {
                continue;
            }

            if (assembly.FullName?.Contains(
                    "Microsoft.GeneratedCode",
                    StringComparison.OrdinalIgnoreCase) == true)
            {
                continue;
            }

            AddAssemblyReference(
                referencePaths,
                assembly);
        }

        foreach (string referencePath in
                 referencePaths)
        {
            parameters.ReferencedAssemblies.Add(
                referencePath);
        }
    }

    private static void AddAssemblyReference(
        ISet<string> referencePaths,
        Assembly assembly)
    {
        if (assembly.IsDynamic)
        {
            return;
        }

        string location;

        try
        {
            location = assembly.Location;
        }
        catch (NotSupportedException)
        {
            return;
        }

        if (string.IsNullOrWhiteSpace(location))
        {
            return;
        }

        if (string.Equals(
                Path.GetFileName(location),
                "mscorlib.dll",
                StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        if (File.Exists(location))
        {
            referencePaths.Add(location);
        }
    }

    private bool DisplayCompilerDiagnostics(
        CompilerResults results)
    {
        if (results.Errors.Count == 0)
        {
            return true;
        }

        bool hasErrors = false;
        StringBuilder builder = new();

        foreach (CompilerError error in
                 results.Errors)
        {
            hasErrors |= !error.IsWarning;

            if (error.Line > 0)
            {
                builder.AppendFormat(
                    "Line {0}, col {1}: ",
                    error.Line,
                    error.Column);
            }

            if (!string.IsNullOrEmpty(
                    error.ErrorNumber))
            {
                builder.AppendFormat(
                    "[{0}] ",
                    error.ErrorNumber);
            }

            builder.Append(error.ErrorText);
            builder.AppendLine();
        }

        using CustomModuleErrors errorDialog =
            new();

        errorDialog.ErrorText =
            builder.ToString();

        errorDialog.Text =
            "Compilation " +
            (hasErrors
                ? "errors"
                : "warnings");

        errorDialog.ShowDialog(this);

        return !hasErrors;
    }

    private void InvokeEvaluator(
        Assembly? assembly)
    {
        if (assembly is null)
        {
            throw new InvalidOperationException(
                "Compilation succeeded, but no assembly was returned.");
        }

        Type evaluatorType =
            assembly.GetType(
                EvaluatorTypeName,
                throwOnError: true)
            ?? throw new TypeLoadException(
                $"The evaluator type '{EvaluatorTypeName}' could not be loaded.");

        object evaluator =
            Activator.CreateInstance(
                evaluatorType)
            ?? throw new InvalidOperationException(
                "The C# evaluator could not be created.");

        MethodInfo evalMethod =
            evaluatorType.GetMethod(
                "EvalCode",
                BindingFlags.Instance |
                BindingFlags.Public)
            ?? throw new MissingMethodException(
                evaluatorType.FullName,
                "EvalCode");

        try
        {
            object? result =
                evalMethod.Invoke(
                    evaluator,
                    null);

            textBox2.Text =
                result?.ToString() ??
                string.Empty;
        }
        catch (TargetInvocationException ex)
            when (ex.InnerException is not null)
        {
            throw new InvalidOperationException(
                "The evaluated C# expression threw an exception.",
                ex.InnerException);
        }
    }

    private void ShowEvaluationError(
        Exception exception)
    {
        Exception displayedException =
            exception.InnerException ??
            exception;

        MessageBox.Show(
            this,
            displayedException.ToString(),
            "C# evaluation error",
            MessageBoxButtons.OK,
            MessageBoxIcon.Error);
    }
}