using System.Windows.Forms;

namespace AutoWikiBrowser;

/// <summary>
/// Displays compilation or runtime errors generated by a custom module.
/// </summary>
/// <remarks>
/// This dialog provides a read-only view of the error text and allows the
/// user to dismiss it after reviewing the reported errors.
/// </remarks>
public partial class CustomModuleErrors : Form
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CustomModuleErrors"/> class.
    /// </summary>
    public CustomModuleErrors()
    {
        InitializeComponent();
    }

    /// <summary>
    /// Sets the error text displayed by the dialog.
    /// </summary>
    public string ErrorText
    {
        set => textBox1.Text = value;
    }

    /// <summary>
    /// Closes the dialog.
    /// </summary>
    /// <param name="sender">
    /// The control that raised the event.
    /// </param>
    /// <param name="e">
    /// Event data associated with the click.
    /// </param>
    private void button1_Click(object sender, System.EventArgs e)
    {
        Close();
    }
}