using Avalonia.Controls;

namespace Twain.UI.Diff;

/// <summary>
/// Displays a side-by-side comparison of original and updated article text.
/// </summary>
/// <remarks>
/// The initial implementation presents two read-only text surfaces. A future
/// implementation will render structured diff output generated by Twain.Core.
/// </remarks>
public partial class DiffView : UserControl
{
    /// <summary>
    /// Initializes the diff view.
    /// </summary>
    public DiffView()
    {
        InitializeComponent();
    }
}