namespace Twain.Core.Lists;

/// <summary>
/// Represents the result of a list-generation operation.
/// </summary>
public sealed class ListGenerationResult
{
    public ListGenerationResult(List<Article> articles)
    {
        ArgumentNullException.ThrowIfNull(articles);

        Articles = articles;
        Failure = ListGenerationFailure.None;
    }

    public ListGenerationResult(
        ListGenerationFailure failure,
        string errorMessage,
        string errorVariable = "")
    {
        if (failure == ListGenerationFailure.None)
        {
            throw new ArgumentException(
                "A failed list-generation result must specify a failure.",
                nameof(failure));
        }

        Failure = failure;
        ErrorMessage = errorMessage ?? string.Empty;
        ErrorVariable = errorVariable ?? string.Empty;
        Articles = new List<Article>();
    }

    /// <summary>
    /// Gets the articles generated by the list provider.
    /// </summary>
    public List<Article> Articles { get; }

    /// <summary>
    /// Gets the known failure that occurred during list generation.
    /// </summary>
    public ListGenerationFailure Failure { get; }

    /// <summary>
    /// Gets the error message associated with the generation failure.
    /// </summary>
    public string ErrorMessage { get; } = string.Empty;

    /// <summary>
    /// Gets the error-specific value associated with the generation failure.
    /// </summary>
    public string ErrorVariable { get; } = string.Empty;

    /// <summary>
    /// Gets a value indicating whether list generation completed successfully.
    /// </summary>
    public bool Succeeded =>
        Failure == ListGenerationFailure.None;
}