<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Twain.UI</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

<ItemGroup>
  <ProjectReference Include="..\Twain.Core\Twain.Core.csproj" />
  <ProjectReference Include="..\Twain.CustomModules\Twain.CustomModules.csproj" />
</ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Downloads\Twainlogo.png" Link="Assets\Twainlogo.png" />

    <AvaloniaResource Include="..\..\..\..\Downloads\TwainSplash.png" Link="Assets\TwainSplash.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />

    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />

    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />

    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />

    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">
        None
      </IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">
        All
      </PrivateAssets>
    </PackageReference>

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ArticleList\ArticleListView.axaml.cs">
      <DependentUpon>ArticleListView.axaml</DependentUpon>
    </Compile>

    <Compile Update="Diff\DiffView.axaml.cs">
      <DependentUpon>DiffView.axaml</DependentUpon>
    </Compile>

    <Compile Update="Disambiguation\DabControl.axaml.cs">
      <DependentUpon>DabControl.axaml</DependentUpon>
    </Compile>

    <Compile Update="Options\OptionsView.axaml.cs">
      <DependentUpon>OptionsView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Nerdbank.GitVersioning" Version="3.10.94" />
  </ItemGroup>

</Project>