<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Twain.UI</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Downloads\Twainlogo.png" Link="Assets\Twainlogo.png" />
    <Content Include="..\..\..\..\Downloads\TwainSplash.png" Link="Assets\TwainSplash.png" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Avalonia" Version="12.1.1" />
	  <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
	  <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
	  <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Twain.Core\Twain.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ArticleList\ArticleListView.axaml.cs">
      <DependentUpon>ArticleListView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Options\OptionsView.axaml.cs">
      <DependentUpon>OptionsView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
