<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>globe.ico</ApplicationIcon>
    <StartupObject>AWBUpdater.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="globe.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
  </ItemGroup>
	<Target Name="CopyUpdaterToAwbOutput" AfterTargets="Build">
		<PropertyGroup>
			<AwbOutputDirectory>$(SolutionDir)AWB\bin\$(Configuration)\</AwbOutputDirectory>
		</PropertyGroup>

		<MakeDir Directories="$(AwbOutputDirectory)" />

		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AwbOutputDirectory)" />
	</Target>
</Project>